# Site settings
title: Oiva Eskola
email: oiva.eskola@gmail.com
description: Full stack web developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://oivaeskola.fi" # the base hostname & protocol for your site
twitter_username: oiva
github_username: oiva
flickr_username: oiva
linkedin_username: oivaeskola

# Conversion
markdown:    kramdown
lsi:         false
excerpt_separator: "\n\n"

# Output
permalink: /:year/:month/:day/:title/
timezone: Europe/Helsinki
paginate: 20
paginate_path: "page:num/"

gems:
  - jekyll-sitemap
  - jekyll-paginate