# Site settings
name: oivaeskola.fi
title: Oiva Eskola
author: Oiva Eskola
author_email: oiva.eskola@gmail.com
email: oiva.eskola@gmail.com
description: Full stack web developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://oivaeskola.fi" # the base hostname & protocol for your site
twitter_username: oiva
github_username: oiva
flickr_username: oiva
linkedin_username: oivaeskola

# Conversion
excerpt_separator: "\n\n"
exclude: [vendor]
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

# Output
permalink: /:year/:month/:day/:title/
timezone: Europe/Helsinki
paginate: 20
paginate_path: "page:num/"

gems:
  - jekyll-sitemap
  - jekyll-paginate

whitelist:
  - jekyll-paginate

quiet: false